title: "voresh lib"
repository: Voresh/voresh.github.io
baseurl: ""
url: "https://voresh.github.io/"

theme: jekyll-theme-console

header_pages:
  - index.md
  - articles.md
  - sources.md
  - books.md
  - vids.md
  - courses.md
  - quotes.md
  - snippets.md
  - portfolio.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: '<a href="mailto:voresh@protonmail.com">[voresh@protonmail.com]</a> <a href="/cv.html">[cv]</a> <a href="https://github.com/Voresh">[github]</a>'

markdown: kramdown
highlighter: rouge
