title: "voresh blog"
baseurl: ""
url: "https://voresh.github.io/"

theme: jekyll-theme-console

header_pages:
  - index.md
  - about.md
  - quotes.md

style: dark # dark (default), light or hacker
# listen_for_clients_preferred_style: true # false (default) or true

footer: 'voresh@protonmail.com'
