title: "voresh blog"
repository: Voresh/voresh.github.io
baseurl: ""
url: "https://voresh.github.io/"

theme: jekyll-theme-console

header_pages:
  - index.md
  - vids.md
  - quotes.md
  - about.md

style: dark # dark (default), light or hacker
# listen_for_clients_preferred_style: true # false (default) or true

footer: '<a href="mailto:voresh@protonmail.com">[voresh@protonmail.com]</a> <a href="/cv.html">[cv]</a>'

markdown: kramdown
highlighter: rouge
